### ISSUE TITLE
Чат при проверке

### ISSUE THREAD

**Issue by WowExotic** [kainlighty/LightCheck#11]
### Plugin Version

2.2.0

### Select The Core

Spigot

### Your requeset

Добавьте пожалуйста чат между проверяющим и кого проверяют, кого проверяют может писать в чат, а вот кто проверяет не может писать, я думаю что-то типа /check msg <сообщение>

Возможность причины, если время на проверке истекает, как отдельная прична для бана

**Comment by kainlighty** [comment]
Приватные сообщение итак есть. Если ты о том, что нет чата у того, кто проверяет, то ему и нет смысла иметь к доступ. Для того, кто на проверке приватный чат добавлен для удобства, дабы проверяющий четко видел отдельное сообщение, это косметика, не более
