### ISSUE TITLE
Возможность отключать hover

### ISSUE THREAD

**Issue by WowExotic** [kainlighty/LightCheck#17]
### Select The Core

Paper

### Description

Добавьте пожалуйста возможность отключить hover, потому что некоторые игроки промахиваются и тыкают признание в читах

**Comment by kainlighty** [comment]
> ### Select The Core
> Paper
> 
> ### Description
> Добавьте пожалуйста возможность отключить hover, потому что некоторые игроки промахиваются и тыкают признание в читах

Привет! Уточни, пожалуйста, где именно нужна такая возможность? С каким сообщением путают и промахиваются?

**Comment by WowExotic** [comment]
> > ### Select The Core
> > Paper
> > ### Description
> > Добавьте пожалуйста возможность отключить hover, потому что некоторые игроки промахиваются и тыкают признание в читах
> 
> Привет! Уточни, пожалуйста, где именно нужна такая возможность? С каким сообщением путают и промахиваются?

Ховер всего один
hover: '&a&l» &fНажмите для подтверждения'

**Comment by WowExotic** [comment]
Можно это реализовать?

**Comment by kainlighty** [comment]
> Можно это реализовать?

Да. Как время будет.

Сейчас у меня очень много работы в Яндексе, когда выцеплю свободное время, пока, к сожалению, не знаю.

Поставил себе задачу в Трекере, чтобы была на глазах, так сказать:
![image](https://github.com/user-attachments/assets/7af08a26-844d-457f-86e1-1b6a501c2cc8)

**Comment by kainlighty** [comment]
> Можно это реализовать?

Да. Как время будет.

Сейчас у меня очень много работы в Яндексе, когда выцеплю свободное время, пока, к сожалению, не знаю.

Поставил себе задачу в Трекере, чтобы была на глазах, так сказать:
![image](https://github.com/user-attachments/assets/fd990d5e-eb5c-4744-acb2-444f90e9bd2a)

**Comment by kainlighty** [comment]
[v2.2.2.1 | Hover message](https://github.com/kainlighty/LightCheck/releases/tag/2.2.2.1)
