### ISSUE TITLE
Throws a lot of errors in the console

### ISSUE THREAD

**Issue by ghost** [kainlighty/LightCheck#2]
### Plugin Version

2.0.6

### Select The Core

Purpur

### Description

I called a person to check, wrote a command to disable the timer and it gave a lot of errors
Errors can be viewed here:https://pastebin.com/93t1tE6j

**Comment by kainlighty** [comment]
What is the 'cheatcheck' command?

Only /check

**Comment by ghost** [comment]
I added an alias (in the plugin.yml file), since the /check command is occupied by the advancedban plugin, this does not affect the functionality of the plugin in any way

**Comment by kainlighty** [comment]
> I added an alias (in the plugin.yml file), since the /check command is occupied by the advancedban plugin, this does not affect the functionality of the plugin in any way

Use main command - /lightcheck..

**Comment by ghost** [comment]
не помогло: https://pastebin.com/mYDQdkiH

**Comment by kainlighty** [comment]
> не помогло: https://pastebin.com/mYDQdkiH

Пасиб конечно что ранее на английском писал)

![image](https://github.com/kainlighty/LightCheck/assets/111251772/2257ae0f-860d-4bc6-b0e6-bea9dcadea55)

plugin.yml верни как было или перекачай плагин

**Comment by ghost** [comment]
бля, я тупой, я забыл после таймера стоп написать, извини, то что время потратил
