### ISSUE TITLE
Босс бар + плагин крашыт + конфиг не сохраняется + ники в табе показываются но когда нажымаешь на таб то оно выбирает в начале команду и потом ники, и всё равно если ты написал ник

### ISSUE THREAD

**Issue by ng25yt** [kainlighty/LightCheck#4]
### Plugin Version

Plugin version: 2.0.6 Server version: 1.16.5

### Select The Core

Purpur

### Description

Если не остановить таймер когда окончилась проврека, **то боссбар будет оставатся всю игру пока не перезашёл!** **Даже если в настройках поставить**  `bossbar: false` **то при проверке боссбар будет всё равно появляться!** 

А иногда после изменения некоторых параметр в плагине или просто **даже когда ничего не трогаешь** просто сидишь на проверке и потом пишешь `/check approve` или ` /check disprove` **то выдается ошибка в чате и в консоли**. Оказывается когда я сменил **параметры в конфиге плагине, то они вообще не сохранились** хотя я много раз их сохранял, писал `/lightcheck reload`, та **даже переапускал сервер** то **плагин просто не сохранял прараметры** на сервере, хотя в конфиге, **они успешно установлены и остаются так как я их менял но не приминяются на сервере** почему то... 

Также ещё другая проблема, заключается в том что когда пишешь `/check ник` но не полностью и **нажимаешь на таб то ники в табе показываются** но когда **нажымаешь на таб то оно выбирает в начале команду и потом ники**, и всё равно если ты написал ник

Иначе, плагин очень хороший и мне безумно нравится, но много таких огромных ошибок, нужно фиксить очень быстро иначе проверки проходить с проблемами в плагине просто будет не реально! Пожалуйста авторы, прошу вас прислушатся ко мне и пофиксить эти баги как можно быстрее! Заранее спасибо!

**Comment by kainlighty** [comment]
1. На счет боссбара знаю. У нас на проекте стоит false, с этим параметром не наблюдаю проблем. С ним разберусь позже.
2. Некоторые параметры меняются только после перезапуска плагина (сделано специально)
3. Никнейм + команды выводятся, ибо к командам еще добавляются подсказки команд (сделано специально).

В итоге реальный баг остается за боссбаром. Остальное работает как я и задумывал.

**Comment by kainlighty** [comment]
А и да, плагин не крашит. Стоит на проекте 24/7. Проблем с этим не наблюдаю.

**Comment by kainlighty** [comment]
Если есть какие-то сведения об этом, то полный стектрейс в студию. И естественно описать после каких действий возникает краш.

Также укажи параметры которые не сохранялись, если посчитаю этот параметр нужным для reload, то внесу такую возможность.

Плагины в паблике - это плагины, которые использую я и в паблике они лишь потому что просто так захотел, мне не жалко. Многие ошибки пропускаются из-за:
1. Я один все тестирую
2. У меня люди которые используют плагины, используют их по моим рекомендациям (т.е. я объясняю что к чему, поэтому лишних действий они не совершают и совершить не могут (им нельзя)).

**Comment by ng25yt** [comment]
> А и да, плагин не крашит. Стоит на проекте 24/7. Проблем с этим не наблюдаю.

ну явно проблема с боссбаром, переустанавливаю плагин увидем ли оно сработает, но подсказки все есть но дело в том что там есть и команды типо approve и disprove после того как я их и прописал то игрок до сих пор остается на проверке та и ещё, плагин мне выводит кучу ошибок в чате и в консоли, и явно я пытался узнать и прочитать что там и всё таки не понял по этому сейчас переустанавливаю плагин

**Comment by ng25yt** [comment]
> 1. На счет боссбара знаю. У нас на проекте стоит false, с этим параметром не наблюдаю проблем. С ним разберусь позже.
> 2. Некоторые параметры меняются только после перезапуска плагина (сделано специально)
> 3. Никнейм + команды выводятся, ибо к командам еще добавляются подсказки команд (сделано специально).
> 
> В итоге реальный баг остается за боссбаром. Остальное работает как я и задумывал.

Так да, я не просто прописавыю /lightcheck reload но даже перезапускаю сервер и изменения всё равно не видно и не работают

**Comment by kainlighty** [comment]
> > А и да, плагин не крашит. Стоит на проекте 24/7. Проблем с этим не наблюдаю.
> 
> ну явно проблема с боссбаром, переустанавливаю плагин увидем ли оно сработает, но подсказки все есть но дело в том что там есть и команды типо approve и disprove после того как я их и прописал то игрок до сих пор остается на проверке та и ещё, плагин мне выводит кучу ошибок в чате и в консоли, и явно я пытался узнать и прочитать что там и всё таки не понял по этому сейчас переустанавливаю плагин

Игрок не может оставаться на проверке, я вчера лично вызывал игрока на проверку, аппрувал и диспрувал, все хорошо.

Стектрейс в студию

**Comment by kainlighty** [comment]
> > 1. На счет боссбара знаю. У нас на проекте стоит false, с этим параметром не наблюдаю проблем. С ним разберусь позже.
> > 2. Некоторые параметры меняются только после перезапуска плагина (сделано специально)
> > 3. Никнейм + команды выводятся, ибо к командам еще добавляются подсказки команд (сделано специально).
> > 
> > В итоге реальный баг остается за боссбаром. Остальное работает как я и задумывал.
> 
> Так да, я не просто прописавыю /lightcheck reload но даже перезапускаю сервер и изменения всё равно не видно и не работают

Персонал настраивал конфиги, после перезапуска они завелись и все как надо работает (тут без моих рекомендаций было). Стоит измененный кфг, все хорошо.

Если не трудно, запиши весь процесс на видео, от настройки до запуска, если что-то будет, то залей на ютуб с доступом по ссылке.
Не иначе как магия, раз у нас все работает :)

**Comment by ng25yt** [comment]
> > > А и да, плагин не крашит. Стоит на проекте 24/7. Проблем с этим не наблюдаю.
> > 
> > 
> > ну явно проблема с боссбаром, переустанавливаю плагин увидем ли оно сработает, но подсказки все есть но дело в том что там есть и команды типо approve и disprove после того как я их и прописал то игрок до сих пор остается на проверке та и ещё, плагин мне выводит кучу ошибок в чате и в консоли, и явно я пытался узнать и прочитать что там и всё таки не понял по этому сейчас переустанавливаю плагин
> 
> Игрок не может оставаться на проверке, я вчера лично вызывал игрока на проверку, аппрувал и диспрувал, все хорошо.
> 
> Стектрейс в студию


Ну у меня он всё равно остается и выдаются ошибки в консоли, поэтому щас попробую переустановит плагин и если будет что то подобное сново, то буду уже обращатся к студии. Спасибо огромное за вашу помощь!

**Comment by ng25yt** [comment]
> > > 1. На счет боссбара знаю. У нас на проекте стоит false, с этим параметром не наблюдаю проблем. С ним разберусь позже.
> > > 2. Некоторые параметры меняются только после перезапуска плагина (сделано специально)
> > > 3. Никнейм + команды выводятся, ибо к командам еще добавляются подсказки команд (сделано специально).
> > > 
> > > В итоге реальный баг остается за боссбаром. Остальное работает как я и задумывал.
> > 
> > 
> > Так да, я не просто прописавыю /lightcheck reload но даже перезапускаю сервер и изменения всё равно не видно и не работают
> 
> Персонал настраивал конфиги, после перезапуска они завелись и все как надо работает (тут без моих рекомендаций было). Стоит измененный кфг, все хорошо.
> 
> Если не трудно, запиши весь процесс на видео, от настройки до запуска, если что-то будет, то залей на ютуб с доступом по ссылке. Не иначе как магия, раз у нас все работает :)

переустанавливаю плагин, если будет сново тоже самое, то запишу и солью на ют с доступом с ссылкой

**Comment by kainlighty** [comment]
> > > > 1. На счет боссбара знаю. У нас на проекте стоит false, с этим параметром не наблюдаю проблем. С ним разберусь позже.
> > > > 2. Некоторые параметры меняются только после перезапуска плагина (сделано специально)
> > > > 3. Никнейм + команды выводятся, ибо к командам еще добавляются подсказки команд (сделано специально).
> > > > 
> > > > В итоге реальный баг остается за боссбаром. Остальное работает как я и задумывал.
> > > 
> > > 
> > > Так да, я не просто прописавыю /lightcheck reload но даже перезапускаю сервер и изменения всё равно не видно и не работают
> > 
> > 
> > Персонал настраивал конфиги, после перезапуска они завелись и все как надо работает (тут без моих рекомендаций было). Стоит измененный кфг, все хорошо.
> > Если не трудно, запиши весь процесс на видео, от настройки до запуска, если что-то будет, то залей на ютуб с доступом по ссылке. Не иначе как магия, раз у нас все работает :)
> 
> переустанавливаю плагин, если будет сново тоже самое, то запишу и солью на ют с доступом с ссылкой

Протестил: approve, disprove, эти же команды после timer stop. Также нажатия на сообщение. Выход при проверке. Все отлично

**Comment by ng25yt** [comment]
> > > > > 1. На счет боссбара знаю. У нас на проекте стоит false, с этим параметром не наблюдаю проблем. С ним разберусь позже.
> > > > > 2. Некоторые параметры меняются только после перезапуска плагина (сделано специально)
> > > > > 3. Никнейм + команды выводятся, ибо к командам еще добавляются подсказки команд (сделано специально).
> > > > > 
> > > > > В итоге реальный баг остается за боссбаром. Остальное работает как я и задумывал.
> > > > 
> > > > 
> > > > Так да, я не просто прописавыю /lightcheck reload но даже перезапускаю сервер и изменения всё равно не видно и не работают
> > > 
> > > 
> > > Персонал настраивал конфиги, после перезапуска они завелись и все как надо работает (тут без моих рекомендаций было). Стоит измененный кфг, все хорошо.
> > > Если не трудно, запиши весь процесс на видео, от настройки до запуска, если что-то будет, то залей на ютуб с доступом по ссылке. Не иначе как магия, раз у нас все работает :)
> > 
> > 
> > переустанавливаю плагин, если будет сново тоже самое, то запишу и солью на ют с доступом с ссылкой
> 
> Протестил: approve, disprove, эти же команды после timer stop. Также нажатия на сообщение. Выход при проверке. Все отлично

У меня тоже в начале было всё окей, но сейчас не знаю что случилось. Может я где-то накосил или что-то не правильное сделал, хотя мне не кажется и как по мне просто баг. Если что, я уже переустановил плагин и переделываю конфигурацию и посмотрим что там будет.

**Comment by kainlighty** [comment]
Как успехи?

**Comment by ng25yt** [comment]
> Как успехи?

Переустановил плагин, СТАЛО ЕЩЕ ХУЖЕ! Все прошлые проблемы решились но теперь появилась новая! Например `/check confirm` нифига не работает та и ещё когда время проверки вышло то чела не банит а его просто отпускает и он идёт спокойно гулять. Вы где такое видели вообще? А ещё хуже следущая ситуация: Когда пишешь `/check disprove` то всё окей чела отпускает типо все норм. Но когда я пишу `/check approve` типо что чел играет с читами то мне в чат пишет Вот этот игрок признался в читах" и просто его отпускает (если что в конфиге всё нормльно настроенно, даже тех админ сказал что всё норм настроенно). Я вообще ахуел, как можно такой фиговый плагин сделать, типо чел играет с читами, я его признаю читером а мне плагин говорит "Пон, чел признался в читах, но мне лень его банить поэтому я его отпущу" или мне как это понимать? Просто не советую этот плагин, в начале показался норм, а теперь хочу всех создателей обматерить. Просто скачал плагин, у тебя уже дофига проблем, переустанавливаешь плагин, и всё прошлые проблемы пропадают но у тебя ещё новые проблемы добавляются та и ещё хуже чем прошлые! Я просто в шоке и никому не советую этот плагин вообще! Суть этого плагина в том что она должна избавлятся от читеров а не наоборот им помогать играть и их отпускает при признание в читах та и ещё мне спокойно пишет в чат что чел признался и отпускает его спокойно дальше играть! Жесть, не советую никому этот плагин (кроме у кого есть читерский сервер и вы хотите проверить чела на читы что бы убедиться что он читер и его оставить играть если хотите) У меня просто нету слов!

**Comment by kainlighty** [comment]
Благодарю за отзыв. 

Если вы нашли баг в плагине, предоставьте стектрейс ошибки, если ошибок в консоли нет, отправьте видео о неработающей функции.

----

Thank you for your feedback. 

If you find a bug in the plugin, provide a stacktrace of the error, if there are no errors in the console, send a video about the broken function.
