### ISSUE TITLE
не ворк автобан после проверки?

### ISSUE THREAD

**Issue by Medved0546** [kainlighty/LightCheck#5]
### Plugin Version

2.0.7

### Select The Core

Paper

### Description

paper 1.16.5
он вообще есть?
https://imgur.com/a/PrzCzHy

**Comment by kainlighty** [comment]
Обнови конфигурации /lightcheck reconfig в консоли.

**Comment by Medved0546** [comment]
/lightcheck reconfig не помогло
вообщем то я перешёл на https://www.spigotmc.org/resources/ultimatecheatcheck-1-12-2-1-20-2.112711/ т.к у мя 1.16
