### ISSUE TITLE
Привет, идея для чеков

### ISSUE THREAD

**Issue by ghost** [kainlighty/LightCheck#6]
### Plugin Version

2.0.7

### Select The Core

Purpur

### Description

Привет, добавь пожалуйста, если человек прошел проверку, то его телепортировало на то место, где он был

**Comment by kainlighty** [comment]
Для этого тебе нужно включить телепорт к стаффу и телепорт назад в конфигурации. Телепорт игрока на прежнее местоположение работает только при условии, что если велючена телепортация к администратору.
