### ISSUE TITLE
Игрок может перезагружать плагин без прав

### ISSUE THREAD

**Issue by ghost** [kainlighty/LightCheck#7]
### Plugin Version

Самая новая

### Select The Core

Purpur

### Description

Игрок может перезагружать плагин без прав

**Comment by ghost** [comment]
так же, когда я пишу таймер стоп(при этом проверка еще не начиналась, то выводит ошибки в консоль)

**Comment by kainlighty** [comment]
Перекачай плагин

**Comment by ghost** [comment]
> Перекачай плагин 
у меня самая новая версия!!!!!

**Comment by kainlighty** [comment]
> > Перекачай плагин 
> 
> у меня самая новая версия!!!!!

Я понимаю, я говорю, перекачай плагин

**Comment by ghost** [comment]
я перекачивал

> > > Перекачай плагин
> > 
> > 
> > у меня самая новая версия!!!!!
> 
> Я понимаю, я говорю, перекачай плагин

**Comment by kainlighty** [comment]
> я перекачивал
> 
> > > > Перекачай плагин
> > > 
> > > 
> > > у меня самая новая версия!!!!!
> > 
> > 
> > Я понимаю, я говорю, перекачай плагин

Я проверил и сам по себе объект Player не может вписывать reload, только из консоли.

**Comment by kainlighty** [comment]
> я перекачивал
> 
> > > > Перекачай плагин
> > > 
> > > 
> > > у меня самая новая версия!!!!!
> > 
> > 
> > Я понимаю, я говорю, перекачай плагин

Я проверил, он просто ничего не выдает

**Comment by ghost** [comment]
в чат ничего не выдает, но в консоли пишет плагин перегружен 

> > я перекачивал
> > > > > Перекачай плагин
> > > > 
> > > > 
> > > > у меня самая новая версия!!!!!
> > > 
> > > 
> > > Я понимаю, я говорю, перекачай плагин
> 
> Я проверил, он просто ничего не выдает
